### ISSUE TITLE
Not working on Windows 2019 

### ISSUE THREAD

**Issue by LDAPAngel** [vletoux/MakeMeEnterpriseAdmin#2]
Am trying to understand how GetNCChanges works and looked at this code as you have done in C#. I don't follow all the code as its on another (god) level !

I could not get this to work on a Windows 2019 server which had AD installed on it and then thought, it was done 8 years ago, so tried on Windows 2016 with AD installed  and voila, it works on 2016.

Debugged it down to  failing in MarshalReplicationData(DRS_MSG_GETCHGREPLY_V6 pmsgOut, out Dictionary<int, object> replicationData)
			
-->  REPLENTINFLIST list = (REPLENTINFLIST)Marshal.PtrToStructure(pObjects, typeof(REPLENTINFLIST));

any advice or could you update for 2019  ?

**Comment by vletoux** [comment]
I see 2 options:
either the data returned in the 2019 case is not correct (aka this is not a 2016 vs 2019 issue)
or there is an issue with the structure returned.

The call is https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-drsr/b63730ac-614c-431c-9501-28d6aca91894 IDL_DRSGetNCChanges and is well documented.

You can see that a version 8 is sent as input and the data parsed is version 6 (since this is a C union structure, this is not an issue)

You should create a c# project and load the code under the debugger.
The black magic with RPC calls is working, so this is only an issue while parsing the data.
It just look at a pointer and convert it to DRS_MSG_GETCHGREPLY_V6

You can run the code step by step and see if that conforms with the c structure (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-drsr/1317a654-5dd6-45ff-af73-919cbc7fbb45)

**Comment by LDAPAngel** [comment]
Appreciate your response.

The code works perfectly, the issue was me ! I was testing this on a Windows 2019 AD where I had modified the DIT, when I tested on another fresh 2019 build it works perfectly. 

One minor thing, I did indeed put all the C# code into visual studio and compiled as x64, this will not work at all (on 2016/2019), The DrsBind fails, however this is not a showstopper as it works on x86 fine.

Also, how can I run this on a workstation and target a remote AD i.e. provide credentials and get the data from an AD running on another server ?

**Comment by vletoux** [comment]
What do you mean by "it does not work" on x64 ?

I used __arglist for x64 call but apparently Microsoft is killing it.
It means that all pinvoke prototype should be made instead of one.

This is what I made on PingCastle and the reason so many NdrClientCall2 exists:
https://github.com/netwrix/pingcastle/blob/master/RPC/nativemethods.cs#L26-L44

**Comment by LDAPAngel** [comment]
I'm using visual studio 2019 and error I get from the line ( there are 4 lines in the code with this same error)

  result = NdrClientCall2x64(GetStubHandle(), GetProcStringHandle(0), __arglist(hBinding, NtdsDsaObjectGuid, extensions_in, out pDrsExtensionsExt, out hDrs));

is

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8378	__arglist cannot have an argument passed by 'in' or 'out'	

I changed it to result = NdrClientCall2x64(GetStubHandle(), GetProcStringHandle(0), __arglist(hBinding, NtdsDsaObjectGuid, extensions_in, pDrsExtensionsExt, hDrs));

i.e. removed the out in the __arglist


and then it compiles, but does not work for x64 (x86 is ok)

**Comment by vletoux** [comment]
this is what I told you.
Replace it with result = NdrClientCall2x64(GetStubHandle(), GetProcStringHandle(0), hBinding, NtdsDsaObjectGuid, extensions_in, out pDrsExtensionsExt, out hDrs);
(aka remove arglist)

and add the pinvoke declaration so it won't complain at compile time

**Comment by LDAPAngel** [comment]
Perfect thanks, any advice on how to run using a remote workstation ?

**Comment by vletoux** [comment]
I don't understand the question.
This code just run RPC call to the DC.

**Comment by LDAPAngel** [comment]
Sorry to clarify, 

If I'm logged on to a member server with just normal user credentials, I'd like to run the code against the DC with supplied credentials that can replicate the changes.

**Comment by vletoux** [comment]
the thread running the code should impersonate the target user.
I don't think you need my help for this part.
